server:
  port : 8095

springdoc:
  swagger-ui.path: /

otus:
  auth:
    private: |
      -----BEGIN PRIVATE KEY-----
      MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDcCJNiF8uDvZQU
      aTCQ0xb4PAnCFsChmLdu63Vcyab1Q91e/L0T27NQ5hzp0v4/zheBLuOxb9073IkW
      G1p6TAvYff2XSb3O0tNOPVuUpkorxWtN2JuGk2YSWKLV6KgWW4So8FW0m6B44B5Y
      VHypPKSc8HhDcPZAKi5dMki/f3FwAqGhJ7dGu9ol2kCwFyBAFh3vESLK80lnRpWk
      u/GdEsgJIli53V+TgIKHavw2+1Rn+27gCulyFKtkxNj51ZUxh2C1fnC8wGSbu6fy
      wiIAz8NH397++H8dH+je0I9SNqrWyVW4VwjuYNdo/UJiC3x2DjCEGDjt4Wif6Mg4
      g/x86C2TAgMBAAECggEBAIFtcfRjdsz5eN9AuNaXtI00E7FdXNYxVMUkL5by7wia
      cN7s3/OMakAN+7f26qNxgRX2FO1MleAea2zbji8eCGHCSqbxM3szPCRrpzEbV8nD
      iMjzvxg8H/BuvuoAvs7X6oLNTDy+xngTrQXcPK/4AgRm1vckvVUk+rzLVUt/laSC
      cFnCrKpa2cIQnReP6IEHN7XRtESV4AHvbGRMmSqizAsKNPN+G/Q+HkT1rffHiw1y
      ftPLjk90X8OCIe/WJnKfCtT7puksawTFsDssFe5Sd0q6jjIBId6GlcprQzXmDBqf
      PTjrPpUiHGXN3I5b3TstbFbh1ad1a6+xMdyZ4fB9rTECgYEA9cyjd03v963H2G8d
      AE6VEwekKUt1ulQM4iypTviuuyyJAwDTZcT3Ba39dMgYSXiqvAsvWTh5znxAmLSS
      PFzzzXtoLyqC4w3j+l9q5u+xmeE9UTuQQTUbpCES2S19HTDVdUO39CvH1frt/HMT
      T23qyk4mucOuXmspVkR9MCD6h/0CgYEA5SozpFU9EYTmObblfCZ47DeLFUSBr3us
      rSmFC5jnETgX3ghISGQLv7AOdEjuhpC25cOQC1nEoAAUHpNiTd444TO/m9AwfS0z
      stRMWIyKK0dpSpGXyk6L5Yh2UBgm90VtaphK062zi4fxiJra7tCGRQSxzwEc2ixE
      ttUK6XTOmM8CgYBIy1cqERHdZ0EFTzrmiV9K6Htso2V1TkkWfqWRtsKAulrFYew5
      epCxxOqIOG5A7BScZi+am8gvJ8s1rlyUte6aT072kP98YPPAhZuyUxBlAzjWou5A
      8YqDHCxp1zfzei/tb6W+EW04aP0sQ6RXZLUhPu3nHBW67r+qRdRReaLYvQKBgQCX
      KPApfKQskyo9dZwH+WSYA8c1PxwAAacUDagZz0DThdmQdowfXAa36UyPfbAAiSJr
      ikTQh+T/2S1sQbF9RZDlU3oXMAtb9l38nrbBTeqxw4f7TO//3THANPQ9vsCtKFmV
      D2GEITamWgSDJAo3rspyajdTIRvD+aFVrE9nUMoZ1wKBgQCMGfDVI8hOcB+yOMw0
      rrgC91tYRQAyG72UKFfOggJBCFkJnNvH2w/a/tsSz8muTm8dD1Z6gdBjQL6Xci2a
      837bHheNScvOB8SgdYrVFJqOGWT46YqpOReqsX7o9NRek4E+kz0gepCSSmC3EKBQ
      b9FDsnpbn2C6/uA4Upt/48lPSg==
      -----END PRIVATE KEY-----



